print("class YabbaDabbaDoo")
print(" def foo")
print("  if foo == 42")
print("   puts 'world hello'")
print("  elsif foo == 24")
print("   puts 'bk201'")
print("  else")
print("   puts 'congrats!'")
print("  end")
print(" end")
print("end")
